### ISSUE TITLE
請問參加方式

### ISSUE THREAD

**Issue by swchen1282** [twaic/fishackathon-taipei2018#2]
您好，想請問參賽的題目選定是根據挑戰題組自己選定一個主題，開發相關的應用，並進行最後的評分嗎？

**Comment by CrystalTu** [comment]
是的，各組別需選定其中一個主題開發相關應用，在最終日提交作品後，經過初審和複審（最後的pitch）選出各獎項。

但不一定需要照挑戰題組中的建議來進行開發，也歡迎提出更有創意的想法！

**Comment by CrystalTu** [comment]
可參考2016年的活動側寫
https://medium.com/oceansays/2016%E5%B9%B4%E5%85%A8%E7%90%83%E9%AD%9A%E5%AE%A2%E6%9D%BE%E5%9C%A8%E5%8F%B0%E5%8C%97-2955c16d05a0

**Comment by swchen1282** [comment]
好的，謝謝您提供的資訊 :)

2018-01-19 16:35 GMT+08:00 Chen-Yi Tu <notifications@github.com>:
