### ISSUE TITLE
賽前訓練投影片

### ISSUE THREAD

**Issue by ryanchao2012** [twaic/fishackathon-taipei2018#4]
專家講座王老師的投影片彙整了許多題目細節與參考資源
請問是否能夠公開讓參賽者參考呢？

**Comment by CrystalTu** [comment]
已上傳，請參考 <>Code 底下的 2018魚客松中文挑戰題組.pdf 和 Fishhackathon_Wang Hui Yu 0127 PPT.pdf 兩份檔案！

**Comment by ryanchao2012** [comment]
謝謝！
